// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEr8dX1eI3pyKAxR9sh03z2rpix-HtdwY',
    appId: '1:105396255555:web:105bb73f3dc5dc4d3f4df6',
    messagingSenderId: '105396255555',
    projectId: 'novedad-bolso',
    authDomain: 'novedad-bolso.firebaseapp.com',
    storageBucket: 'novedad-bolso.firebasestorage.app',
    measurementId: 'G-D78VFPB59K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJK6JJ8-zxwYBrb-qhcwZyDvHd3G8ceU',
    appId: '1:105396255555:android:48227972cdd41e9d3f4df6',
    messagingSenderId: '105396255555',
    projectId: 'novedad-bolso',
    storageBucket: 'novedad-bolso.firebasestorage.app',
  );
}
